install:
	sudo mkdir /opt/shutdown-when-idle-empty
	sudo cp check_active_users.bash /opt/shutdown-when-idle-empty/.
	sudo cp current_cpu_idle.bash /opt/shutdown-when-idle-empty/.
	sudo cp monitor_usage_and_activity.py /opt/shutdown-when-idle-empty/.
	sudo cp shutdown-when-idle-empty.service /lib/systemd/system/.
