WHEREAMI=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

LS_COLORS='no=00;37:fi=00:di=00;33:ln=04;36:pi=40;33:so=01;35:bd=40;33;01:*.pdf=00;95'
export LS_COLORS
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

# The following lines were added by compinstall
zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' matcher-list '' 'l:|=* r:|=*' 'l:|=* r:|=*' 'l:|=* r:|=*' 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' menu select=1
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle :compinstall filename '/home/amsesk/.zshrc'

bindkey -v '^?' backward-delete-char

autoload -Uz compinit
compinit
# End of lines added by compinstall

. $WHEREAMI/.zshrc_local

# History things
setopt INC_APPEND_HISTORY
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY
export HISTFILE=~/.zhistory
export HISTTIMEFORMAT="[%D]"
export HISTFILESIZE=1000000000
export HISTSIZE=1000000000
export SAVEHIST=1000000000
export R_LIBS_USER="/home/ubuntu/R/x86_64-pc-linux-gnu-library/4.1/"

icat () {
    kitty +kitten icat $1
}
pyenv () {
    source ~/pyenvs/$1/bin/activate
}

# Prompt
if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
	local_or_remote="%F{#dcde7b}[remote]%f"
else
	local_or_remote="%F{#ab3834}[local]%f"
fi
PROMPT="${local_or_remote} %F{#f3dab1}%n@%M%f %F{#2f97c6}%3/%f %F{#cc8a3e}>>>%f "

alias ls="ls --color=auto"
alias history="history 0"
alias lsblk="lsblk -o NAME,UUID,SIZE,TYPE,MOUNTPOINTS"

awsmnt() {
    if [ ! -z SAWSMOUNTDIR ]; then
        sshfs ubuntu@${1}:/home/ubuntu $AWSMOUNTDIR 
    else
        echo "AWSMOUNTDIR unset"
        exit 1
    fi
}

# Useful tools
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(zoxide init zsh)"

# Node
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
